language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-progress --prefer-source
  - npm install -g jshint

script:
  - find src \( -name '*.php' \) -exec php -lf {} \;
  - jshint src
  - phpunit
